### PR TITLE
List of the Question

### PR DESCRIPTION
**Pull request by harshdavedev**
List of the questions and answers button added.

On click of item navigate to Details activity.

### CODE REVIEW

**Comment by christianrei** [comment]
Hi Harshdave. I noticed when running the code that when I change the question or answer of one of the items the saved result isn't shown on the main screen. Could the saving functionality be fixed?

**Comment by harshdavedev** [comment]
Hi Christian,

Yes, I can fix the functionality. if you want I will do that.

**Comment by christianrei** [comment]
It doesn't currently meet the requirements in the README file so it would need to be changed unless you would like this to be your final submission. Up to you.

**Comment by harshdavedev** [comment]
fixed the saving functionality.

**Comment by harshdavedev** [comment]
Hi Christian,

I have fixed the saving  functionality. please check it and let me know.

**Pull request closed without merging**
